---
- name: "[SET UP] tmp folder"
  file:
    path: '{{ tmp_folder }}'
    state: directory


- name: "[RHPAM] Configure Service Account"
  include_tasks: serviceaccount.yml


- name: "[RHPAM] Trial Plan"
  block:
    - name: "[RHPAM] Set defaults"
      set_fact:
        eap_admin_pwd: "{{ default_trial_pwd }}"
        kie_admin_pwd: "{{ default_trial_pwd }}"
        kieserver_db_pwd: "{{ default_trial_pwd }}"
        kie_execution_pwd: "{{ default_trial_pwd }}"
        businesscentral_maven_repo_pwd: "{{ default_trial_pwd }}"
        controller_user: "{{ controller_user_default }}"
        controller_pwd: "{{ default_trial_pwd }}"
        controller_svc: "{{ application_name }}-rhpamcentr"
        has_rhpamcentr: true

    - name: "[RHPAM] Deploy Business Central"
      include_role:
        name: deploy-businesscentral
      vars:
        businesscentral_deployment_name: "{{ controller_svc }}"

    - name: "[RHPAM] Deploy KIE Process Server"
      include_role:
        name: deploy-kieserver
      vars:
        kieserver_mode: 'development'
        kieserver_db_type: 'H2'
        kieserver_replicas: 1
        kieserver_startup_strategy: "{{ apb_kieserver_startup_strategy | default('ControllerBasedStartupStrategy', true) | trim }}"
  when: _apb_plan_id == "trial"

- name: "[RHPAM] Authoring Plan"
  block:
    - name: "[RHPAM] Set defaults"
      set_fact:
        controller_svc: "{{ application_name }}-rhpamcentr"
        has_rhpamcentr: true

    - name: "[RHPAM] Deploy Business Central"
      include_role:
        name: deploy-businesscentral
      vars:
        businesscentral_deployment_name: "{{ controller_svc }}"

    - name: "[RHPAM] Deploy KIE Process Server"
      include_role:
        name: deploy-kieserver
      vars:
        kieserver_replicas: 1
        kieserver_startup_strategy: "{{ apb_kieserver_startup_strategy | default('ControllerBasedStartupStrategy', true) | trim }}"
  when: _apb_plan_id == "authoring"


- name: "[RHPAM] Managed Plan"
  block:
    - name: "[RHPAM] Set defaults"
      set_fact:
        controller_svc: "{{ application_name }}-rhpamcentrmon"
        smartrouter_deployment_name: "{{ application_name }}-smartrouter"

    - name: "[RHPAM] Deploy Business Central Monitoring"
      include_role:
        name: deploy-businesscentral-monitoring
      vars:
        businesscentral_deployment_name: "{{ controller_svc }}"

    - name: "[RHPAM] Deploy Smart Router"
      include_role:
        name: deploy-smartrouter

    - name: "[RHPAM] Deploy KIE Process Server"
      include_role:
        name: deploy-kieserver
      vars:
        has_router: true
        router_svc: "{{ smartrouter_deployment_name }}"
        kieserver_deployment_index: "{{ item }}"
        kieserver_startup_strategy: "{{ apb_kieserver_startup_strategy | default('ControllerBasedStartupStrategy', true) | trim }}"
      with_sequence: start=0 count={{ kie_execution_sets }}
  when: _apb_plan_id == "managed"

- name: "[RHPAM] Immutable Monitor Plan"
  block:
    - name: "[RHPAM] Set defaults"
      set_fact:
        controller_svc: "{{ application_name }}-rhpamcentrmon"
        smartrouter_deployment_name: "{{ application_name }}-smartrouter"

    - name: "[RHPAM] Deploy Business Central Monitoring"
      include_role:
        name: deploy-businesscentral-monitoring
      vars:
        businesscentral_deployment_name: "{{ controller_svc }}"

    - name: "[RHPAM] Deploy Smart Router"
      include_role:
        name: deploy-smartrouter
  when: _apb_plan_id == "immutable-mon"

- name: "[RHPAM] Immutable KIE Server Plan"
  include_role:
    name: deploy-kieserver
  vars:
    kieserver_mgmt_disabled: true
    kieserver_startup_strategy: "{{ apb_kieserver_startup_strategy | default('LocalContainersStartupStrategy', true) | trim }}"
    has_external_controller: true
    has_router: true
    kieserver_s2i: true
  when: _apb_plan_id == "immutable-kie"

- debug:
    msg: "[WARNING] REMOVE NEXT TASK WHEN https://github.com/ansible/ansible/issues/42302 IS SOLVED"

- name: "[RHPAM] remove ReplicationControllers"
  shell: "oc delete rc -l application={{ application_name }} -n {{ namespace }}"
  when: state == "absent"

- name: "[RHPAM] Fail if there were errors"
  fail: msg="[Bundle Failed! - Plan - '{{ _apb_plan_id }}']"
  when: provision_failed
