---
sudo: required
sevices:
  - docker

language: python
python:
  - '2.7'

env:
  - OPENSHIFT_VERSION=v3.9
    #- OPENSHIFT_VERSION=v3.10
    #- KUBERNETES_VERSION=v1.9.0 --> ImageStreams don't work on K8S
    #- KUBERNETES_VERSION=v1.10.0 --> ImageStreams don't work on K8S
# Allow failures on oc latest
# TODO: re-enable latest when it isn't busted
matrix:
  allow_failures:
    - env: KUBERNETES_VERSION=v1.9.0
    - env: OPENSHIFT_VERSION=v3.10
    - env: KUBERNETES_VERSION=v1.10.0

script:
  # Configure test values
  - export apb_name='rhpam-apb'
  - export dockerfile='Dockerfile-canary'
  - export resources='https://github.com/jboss-container-images/rhpam-7-openshift-image/raw/rhpam70-dev/rhpam70-image-streams.yaml'
  - export resources_namespace='openshift'

  # Download test shim.
  - wget -O ${PWD}/apb-test.sh https://raw.githubusercontent.com/ruromero/apb-test-shim/cekit-apb/apb-test.sh
  - chmod +x ${PWD}/apb-test.sh

  # Run tests.
  - ${PWD}/apb-test.sh