---
- name: "[BUSINESS CENTRAL] check requirements"
  include_role:
    name: check-image-requirements
  vars:
    image_namespace: "{{ businesscentral_image_namespace }}"
    image_name: "{{ businesscentral_image_name }}"
    image_tag: "{{ businesscentral_image_tag }}"
  when: state == "present"

- name: "[BUSINESS CENTRAL] configure application"
  block:
    - name: "[BUSINESS CENTRAL] configure services"
      include_tasks: services.yml

    - name: "[BUSINESS CENTRAL] configure routes"
      include_tasks: routes.yml

    - name: "[BUSINESS CENTRAL] configure persistence"
      include_tasks: persistence.yml
      when: businesscentral_volume_size != ""

    - name: "[BUSINESS CENTRAL] Set default secret name if none provided"
      set_fact:
        bc_secret_name: "{{ businesscentral_secret_name | default(businesscentral_default_secret_name, true) }}"

    - name: "[BUSINESS CENTRAL] generate secret if not present"
      include_role:
        name: generate-secret
      vars:
        app_name: '{{ businesscentral_deployment_name }}'
        secret_name: '{{ bc_secret_name }}'
        service_name: '{{ businesscentral_service_name }}'
        keystore_name: '{{ businesscentral_keystore_name }}'
        keystore_alias: '{{ businesscentral_keystore_alias }}'
        keystore_pwd: '{{ businesscentral_keystore_pwd }}'
        route_host: '{{ bc_host }}'

    - name: "[BUSINESS CENTRAL] deploy business central"
      k8s:
        state: '{{ state }}'
        definition: "{{ lookup('template', 'businesscentral-dc.yml.j2') | from_yaml }}"

  when: not provision_failed
