---
- name: "[BUSINESS CENTRAL] set persistent volume claim state to {{ state }}"
  k8s:
    state: '{{ state }}'
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: '{{ businesscentral_deployment_name }}-data'
        namespace: '{{ namespace }}'
        labels:
          app: '{{ businesscentral_deployment_name }}'
          application: '{{ application_name }}'
          service: '{{ businesscentral_service_name }}'
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: '{{ businesscentral_volume_size }}'
