---
state: present

application_name: "rhpam-{{ _apb_plan_id }}"
tmp_folder: /tmp/rhpam

# Whether we are in a cluster or not.
pod_name: "{{ lookup('env', 'POD_NAME') }}"
pod_namespace: "{{ lookup('env', 'POD_NAMESPACE') }}"
in_cluster: "{{ True if (pod_name and pod_namespace) else False }}"