---
- block:
    - name: "[KIE SERVER] Check HA configuration is valid"
      shell: >
        echo "[Invalid HA Configuration] - H2 database cannot be used with a clustered KIE Server. Choose a different option." > /dev/termination-log

    - set_fact:
        provision_failed: true
  when:
    - kieserver_db_type == 'H2'
    - kieserver_replicas > 1
