---
- name: "[MYSQL] check requirements"
  include_role:
    name: check-image-requirements
  vars:
    image_namespace: "{{ mysql_image_namespace }}"
    image_name: "{{ mysql_image_name }}"
    image_tag: "{{ mysql_image_tag }}"
  when: state == "present"

- name: "[MYSQL] configure application"
  block:
    - name: "[MYSQL] configure services"
      include_tasks: services.yml

    - name: "[MYSQL] configure persistence"
      include_tasks: persistence.yml
      when: mysql_volume_size != ""

    - name: "[MYSQL] set deployment config state to {{ state }}"
      k8s:
        state: '{{ state }}'
        definition: "{{ lookup('template', 'mysql-dc.yml.j2') | from_yaml }}"
  when: not provision_failed
