---
- name: "[BUSINESS CENTRAL MONITORING] set https route state to {{ state }}"
  openshift_raw:
    state: '{{ state }}'
    definition:
      apiVersion: v1
      kind: Route
      name: '{{ businesscentral_monitoring_deployment_name }}'
      namespace: '{{ namespace }}'
      labels:
        app: '{{ application_name }}'
        service: '{{ businesscentral_monitoring_service_name }}'
      spec:
        host: '{{ businesscentral_monitoring_hostname }}'
        port:
          targetPort: https
        tls:
          termination: passthrough
          insecureEdgeTerminationPolicy: Redirect
        to:
          kind: Service
          name: '{{ businesscentral_monitoring_deployment_name }}'
  register: route_raw

- name: "[BUSINESS CENTRAL MONITORING] set route host"
  set_fact:
    bcm_host: "{{ route_raw.result.spec.host }}"
  when: state == 'present'
