---
- name: "[BUSINESS CENTRAL MONITORING] set https route state to {{ state }}"
  k8s:
    state: '{{ state }}'
    definition:
      apiVersion: v1
      kind: Route
      metadata:
        name: '{{ businesscentral_deployment_name }}'
        namespace: '{{ namespace }}'
        labels:
          app: '{{ businesscentral_deployment_name }}'
          application: '{{ application_name }}'
          service: '{{ businesscentral_service_name }}'
      spec:
        host: '{{ businesscentral_hostname }}'
        port:
          targetPort: https
        tls:
          termination: passthrough
          insecureEdgeTerminationPolicy: Redirect
        to:
          kind: Service
          name: '{{ businesscentral_deployment_name }}'
  register: route_raw

- name: "[BUSINESS CENTRAL MONITORING] set route host"
  set_fact:
    bcm_host: "{{ route_raw.result.spec.host }}"
  when: state == 'present'
