---
- name: "[SMART ROUTER] set persistent volume claim state to {{ state }}"
  k8s:
    state: '{{ state }}'
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: '{{ smartrouter_deployment_name }}-data'
        namespace: '{{ namespace }}'
        labels:
          app: '{{ smartrouter_deployment_name }}'
          application: '{{ application_name }}'
          service: '{{ smartrouter_service_name }}'
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: '{{ smartrouter_volume_size }}'
