---
- name: "[SMART ROUTER] set https route state to {{ state }}"
  k8s:
    state: '{{ state }}'
    definition:
      apiVersion: v1
      kind: Route
      metadata:
        name: '{{ smartrouter_deployment_name }}'
        namespace: '{{ namespace }}'
        labels:
          app: '{{ smartrouter_deployment_name }}'
          application: '{{ application_name }}'
          service: '{{ smartrouter_service_name }}'
      spec:
        host: '{{ smartrouter_hostname }}'
        to:
          kind: Service
          name: '{{ smartrouter_deployment_name }}'
  register: route_raw
