---
- name: "[SMART ROUTER] set service state to {{ state }}"
  k8s:
    state: '{{ state }}'
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ smartrouter_deployment_name }}'
        namespace: '{{ namespace }}'
        labels:
          app: '{{ smartrouter_deployment_name }}'
          application: '{{ application_name }}'
          service: '{{ smartrouter_service_name }}'
        annotations:
          description: The smart router server http and https ports.
      spec:
        selector:
          deploymentConfig: '{{ smartrouter_deployment_name }}'
        ports:
          - name: http
            port: 9000
            targetPort: 9000
          - name: https
            port: 9443
            targetPort: 9443
