---
kieserver_image_name: "{{ apb_kieserver_image_stream_name | default('rhpam73-kieserver-openshift') }}"
kieserver_image_tag: "{{ image_stream_tag }}"
kieserver_image_namespace: "{{ image_stream_namespace }}"

kieserver_image_pull_policy: IfNotPresent

has_rhpamcentr: false
has_router: false
has_external_controller: false
kieserver_s2i: false
kieserver_sets: "{{ apb_kieserver_sets | default(1, true) }}"
kieserver_replicas: "{{ apb_kieserver_replicas | default(3, true) | trim }}"
kieserver_deployment_index: "0"
kieserver_deployment_name: "{{ application_name }}-kieserver-{{ kieserver_deployment_index }}"
kieserver_default_secret_name: "{{ kieserver_deployment_name }}"
kieserver_service_name: "rhpam-kieserver"
kieserver_businesscentral_maven_svc: "{{ controller_svc }}"
kieserver_hostname: "{{ apb_kieserver_hostname | default('', true) | trim }}"
kieserver_volume_size: "{{ apb_kieserver_volume_size | default('', true) | trim }}"
kieserver_limits_memory: "1Gi"
kieserver_secret_name: "{{ apb_kieserver_secret_name | default('', true) | trim }}"
kieserver_keystore_name: "{{ apb_kieserver_keystore_name | default('keystore.jks', true) | trim }}"
kieserver_keystore_alias: "{{ apb_kieserver_keystore_alias | default('jboss', true) | trim }}"
kieserver_keystore_pwd: "{{ apb_kieserver_keystore_pwd | default(lookup('password', tmp_folder + '/keystore_pwd chars=ascii_letters,digits length=8'), true) }}"

router_svc: "{{ apb_router_svc | default('', true) | trim }}"
router_host:  "{{ apb_router_host | default('', true) | trim }}"
router_port: "{{ apb_router_port | default('', true) | trim }}"
router_protocol: "{{ apb_router_protocol | default('', true) | trim }}"

controller_svc: "{{ apb_controller_svc | default('', true) | trim }}"
controller_host: "{{ apb_controller_host | default('', true) | trim }}"
controller_port: "{{ apb_controller_port | default('', true) | trim }}"
controller_protocol: "{{ apb_controller_protocol | default('', true) | trim }}"
controller_token: "{{ apb_controller_token | default('', true) | trim }}"

kieserver_mgmt_disabled: false

kieserver_db_type: "{{ apb_kieserver_db_type }}"
kieserver_db_size: "{{ apb_kieserver_db_size | default('', true) | trim  }}"

kieserver_db_name: rhpam7
kieserver_db_user: rhpam
kieserver_db_pwd: "{{ lookup('password', tmp_folder + '/db_pwd chars=ascii_leters,digits') }}"

kieserver_db:
  H2:
    driver: h2
    dialect: org.hibernate.dialect.H2Dialect
  PostgreSQL:
    driver: postgresql
    dialect: org.hibernate.dialect.PostgreSQLDialect
    port: 5432
  MySQL:
    driver: mysql
    dialect: org.hibernate.dialect.MySQL57Dialect
    port: 3306
  External:
    driver: "{{ apb_kieserver_external_db_driver | default('', true) | trim }}"
    dialect: "{{ apb_kieserver_external_db_dialect | default('', true) | trim }}"
    host: "{{ apb_kieserver_external_db_host | default('', true) | trim }}"
    port: "{{ apb_kieserver_external_db_port | default('', true) | trim }}"
    name: "{{ apb_kieserver_external_db_name | default('', true) | trim }}"
    url: "{{ apb_kieserver_external_db_url | default('', true) | trim }}"

# SSO Integration
kieserver_sso_client: "{{ apb_kieserver_sso_client | default('', true) | trim }}"
kieserver_sso_client_secret: "{{ apb_kieserver_sso_client_secret | default('', true) | trim }}"

# S2I Integration
kieserver_source_url: "{{ apb_kieserver_source_url | default('', true) | trim }}"
kieserver_source_ref: "{{ apb_kieserver_source_ref | default('', true) | trim }}"
kieserver_source_context: "{{ apb_kieserver_source_context | default('', true) | trim }}"
kieserver_github_webhook_secret: "{{ apb_kieserver_github_webhook_secret | default(lookup('password', tmp_folder + '/github_webhook chars=ascii_letters,digits length=8'), true) }}"
kieserver_generic_webhook_secret: "{{ apb_kieserver_generic_webhook_secret | default(lookup('password', tmp_folder + '/generic_webhook chars=ascii_letters,digits length=8'), true) }}"
kieserver_artifact_dir: "{{ apb_kieserver_artifact_dir | default('', true) | trim }}"
kieserver_container_deployment: "{{ apb_kieserver_container_deployment | default('', true) | trim }}"
