---
- name: "[AMQ] check requirements"
  include_role:
    name: check-image-requirements
  vars:
    image_namespace: "{{ amq_image_namespace }}"
    image_name: "{{ amq_image_name }}"
    image_tag: "{{ amq_image_tag }}"
  when: state == "present"

- name: "[AMQ] Configure AMQ queues"
  set_fact:
    kieserver_jms_amq_queues: "{{ kieserver_jms_queue_executor }},{{ kieserver_jms_queue_request }},{{ kieserver_jms_queue_response}},{{ kieserver_jms_queue_signal }},{{ kieserver_jms_queue_audit }}"
  when:
    kieserver_jms_amq_queues == ""

- name: "[AMQ] Debug AMQ queues"
  debug:
    msg:  kieserver_jms_amq_queues = {{ kieserver_jms_amq_queues }}

- name: "[AMQ] configure application"
  block:
    - name: "[AMQ] configure services"
      include_tasks: services.yml

    - name: "[AMQ] configure route"
      include_tasks: route.yml

    - name: "[AMQ] set deployment config state to {{ state }}"
      k8s:
        state: '{{ state }}'
        definition: "{{ lookup('template', 'amq-dc.yml.j2') | from_yaml }}"
  when: not provision_failed

