---
kieserver_image_name: rhpam70-kieserver-openshift
kieserver_image_tag: 1.0
kieserver_image_namespace: openshift

kieserver_default_secret_name: "{{ application_name }}-kieserver"
kieserver_image_pull_policy: IfNotPresent

kieserver_ha: "{{ apb_ha | default(false) }}"
has_rhpamcentr: false
has_router: false
has_external_controller: false

kieserver_replicas: 1
kieserver_replicas_ha: 3

kieserver_deployment_name: "{{ application_name }}-kieserver"
kieserver_service_name: "rhpam-kieserver"
kieserver_businesscentral_maven_svc: "{{ controller_svc }}"
kieserver_hostname: "{{ abp_kie_execution_hostname | default('', true) | trim }}"
kieserver_volume_size: "{{ apb_kieserver_volume_size | default('', true) | trim }}"
kieserver_limits_memory: "{{ apb_kie_execution_limits_memory }}"
kieserver_secret_name: "{{ apb_kie_execution_secret_name | default('', true) | trim }}"
kieserver_keystore_name: "{{ apb_kie_execution_keystore_name | default('', true) | trim }}"
kieserver_keystore_alias: "{{ apb_kie_execution_keystore_alias | default('', true) | trim }}"
kieserver_keystore_pwd: "{{ apb_kie_execution_keystore_pwd | default(lookup('password', tmp_folder + '/keystore_pwd chars=ascii_letters,digits length=8'), true) }}"

router_svc: "{{ apb_router_svc | default('', true) | trim }}"
router_host:  "{{ apb_router_host | default('', true) | trim }}"
router_port: "{{ apb_router_port | default('', true) | trim }}"
router_protocol: "{{ apb_router_protocol | default('', true) | trim }}"

controller_svc: "{{ apb_controller_svc | default('', true) | trim }}"
controller_user: "{{ apb_controller_user | default('', true) | trim }}"
controller_pwd: "{{ apb_controller_pwd | default('', true) | trim }}"
controller_host: "{{ apb_controller_host | default('', true) | trim }}"
controller_port: "{{ apb_controller_port | default('', true) | trim }}"
controller_protocol: "{{ apb_controller_protocol | default('', true) | trim }}"
controller_token: "{{ apb_controller_token | default('', true) | trim }}"

kieserver_mgmt_disabled: false
kieserver_startup_strategy: LocalContainersStartupStrategy

kieserver_db_type: "{{ apb_kie_execution_db_type }}"
kieserver_db_size: "{{ apb_kie_execution_db_size | default('', true) | trim  }}"

kieserver_db_name: rhpam7
kieserver_db_user: rhpam
kieserver_db_pwd: "{{ lookup('password', tmp_folder + '/db_pwd chars=ascii_leters,digits') }}"

kieserver_db:
  H2:
    driver: h2
    dialect: org.hibernate.dialect.H2Dialect
  PostgreSQL:
    driver: postgresql
    dialect: org.hibernate.dialect.PostgreSQLDialect
    port: 5432
  MySQL:
    driver: mysql
    dialect: org.hibernate.dialect.MySQL5Dialect
    port: 3306

# SSO Integration
kieserver_sso_client: "{{ apb_sso_kie_execution_client | default('', true) | trim }}"
kieserver_sso_client_secret: "{{ apb_sso_kie_execution_client_secret | default('', true) | trim }}"
