---
- name: "[BUSINESS CENTRAL] set service state to {{ state }}"
  k8s_v1_service:
    name: '{{ businesscentral_deployment_name }}'
    namespace: '{{ namespace }}'
    state: '{{ state }}'
    labels:
      app: '{{ application_name }}'
      service: '{{ businesscentral_service_name }}'
    selector:
      app: '{{ application_name }}'
      service: '{{ businesscentral_service_name }}'
      deploymentconfig: '{{ businesscentral_deployment_name }}'
    ports:
      - name: http
        port: 8080
        target_port: 8080
      - name: https
        port: 8443
        target_port: 8443
      - name: git-ssh
        port: 8001
        target_port: 8001

- name: "[BUSINESS CENTRAL] set https route state to {{ state }}"
  openshift_v1_route:
    name: '{{ businesscentral_deployment_name }}'
    namespace: '{{ namespace }}'
    state: '{{ state }}'
    labels:
      app: '{{ application_name }}'
      service: '{{ businesscentral_service_name }}'
    tls_termination: passthrough
    tls_insecure_edge_termination_policy: Redirect
    to_name: '{{ businesscentral_deployment_name }}'
    spec_port_target_port: https
    spec_host: '{{ businesscentral_hostname }}'
  register: route_raw

- name: "[BUSINESS CENTRAL] set persistent volume claim state to {{ state }}"
  k8s_v1_persistent_volume_claim:
    name: '{{ businesscentral_deployment_name }}-data'
    namespace: '{{ namespace }}'
    state: "{{ state }}"
    labels:
      app: '{{ application_name }}'
      service: '{{ businesscentral_service_name }}'
    access_modes:
      - ReadWriteOnce
    resources_requests:
      storage: '{{ businesscentral_volume_size }}'
  when: businesscentral_volume_size != ""

- name: "[BUSINESS CENTRAL] Set default secret name if none provided"
  set_fact:
    bc_secret_name: "{{ businesscentral_secret_name | default(businesscentral_default_secret_name, true) }}"

- name: "[BUSINESS CENTRAL] generate secret if not present"
  include_role:
    name: generate-secret
  vars:
    secret_name: '{{ bc_secret_name }}'
    service_name: '{{ businesscentral_service_name }}'
    keystore_name: '{{ businesscentral_keystore_name }}'
    keystore_alias: '{{ businesscentral_keystore_alias }}'
    keystore_pwd: '{{ businesscentral_keystore_pwd }}'
    route_host: '{{ route_raw.route.spec.host }}'

- name: "[BUSINESS CENTRAL] deploy business central"
  block:
  - name: "[BUSINESS CENTRAL] process deployment config template"
    template:
      src: businesscentral-dc.yml.j2
      dest: '{{ tmp_folder }}/businesscentral-dc.yml'
    register: dc_raw

  - name: "[BUSINESS CENTRAL] create deployment config from template"
    openshift_v1_deployment_config:
      name: '{{ businesscentral_deployment_name }}'
      namespace: '{{ namespace }}'
      state: present
      src: '{{ dc_raw.dest | default(dc_raw.path) }}'
  when: state == "present"

- name: "[BUSINESS CENTRAL] remove Business central deployment config"
  openshift_v1_deployment_config:
    name: '{{ businesscentral_deployment_name }}'
    namespace: '{{ namespace }}'
    state: absent
  when: state == "absent"
