---
- name: "[POSTGRESQL] check requirements"
  include_role:
    name: check-image-requirements
  vars:
    image_namespace: "{{ postgresql_image_namespace }}"
    image_name: "{{ postgresql_image_name }}"
    image_tag: "{{ postgresql_image_tag }}"
  when: state == "present"

- name: "[POSTGRESQL] configure application"
  block:
    - name: "[POSTGRESQL] configure services"
      include_tasks: services.yml

    - name: "[POSTGRESQL] configure persistence"
      include_tasks: persistence.yml
      when: postgresql_volume_size != ""

    - name: "[POSTGRESQL] set deployment config state to {{ state }}"
      k8s:
        state: '{{ state }}'
        definition: "{{ lookup('template', 'postgresql-dc.yml.j2') | from_yaml }}"
  when: not provision_failed
