---
- name: "[POSTGRESQL] set service state to {{ state }}"
  k8s:
    state: '{{ state }}'
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ deployment_name }}'
        namespace: '{{ namespace }}'
        labels:
          app: '{{ kieserver_deployment_name }}'
          application: '{{ application_name }}'
          service: '{{ service_name }}'
      spec:
        selector:
          deploymentConfig: '{{ deployment_name }}'
        ports:
        - name: port-5432
          port: 5432
          protocol: TCP
          targetPort: 5432
