---
- name: "[KIE SERVER {{ kieserver_deployment_index }}] check requirements"
  block:
    - include_role:
        name: check-image-requirements
      vars:
        image_namespace: "{{ kieserver_image_namespace }}"
        image_name: "{{ kieserver_image_name }}"
        image_tag: "{{ kieserver_image_tag }}"

    - include_tasks: check-kie-configuration.yml
  when: state == "present"

- name: "[KIE SERVER {{ kieserver_deployment_index }}] configure application"
  block:
    - name: "[KIE SERVER {{ kieserver_deployment_index }}] configure services"
      include_tasks: services.yml

    - name: "[KIE SERVER {{ kieserver_deployment_index }}] configure routes"
      include_tasks: routes.yml

    - name: "[KIE SERVER {{ kieserver_deployment_index }}] set default secret name if none provided"
      set_fact:
        ks_secret_name: "{{ kieserver_secret_name | default(kieserver_default_secret_name, true) }}"

    - name: "[KIE SERVER {{ kieserver_deployment_index }}] generate secret if not present"
      include_role:
        name: generate-secret
      vars:
        app_name: '{{ kieserver_deployment_name }}'
        secret_name: '{{ ks_secret_name }}'
        service_name: '{{ kieserver_service_name }}'
        keystore_name: '{{ kieserver_keystore_name }}'
        keystore_alias: '{{ kieserver_keystore_alias }}'
        keystore_pwd: '{{ kieserver_keystore_pwd }}'
        route_host: '{{ ks_host }}'

    - name: "[KIE SERVER {{ kieserver_deployment_index }}] configure persistence"
      include_tasks: persistence.yml
      when:
        - kieserver_db_size != ""
        - kieserver_db_type == "H2"

    - name: "[KIE SERVER {{ kieserver_deployment_index }}] set db facts for any DB"
      set_fact:
        # e.g. authoring-postgresql-0
        kieserver_db_deployment: '{{ application_name }}-{{ kieserver_db_type | lower }}-{{ kieserver_deployment_index }}'
        # e.g. rhpam-postgresql
        kieserver_db_service: '{{ kieserver_service_name }}-{{ kieserver_db_type | lower }}'
        kieserver_db_host: '{{ application_name }}-{{ kieserver_db_type | lower }}-{{ kieserver_deployment_index }}'
      when:
        - kieserver_db_type != 'External'
        - kieserver_db_type != 'H2'

    - name: "[KIE SERVER {{ kieserver_deployment_index }}] set db facts for External DB"
      set_fact:
        kieserver_db_host: '{{ kieserver_db[kieserver_db_type].host }}'
        kieserver_db_name: '{{ kieserver_db[kieserver_db_type].name }}'
      when: kieserver_db_type == 'External'

    - name: "[KIE SERVER {{ kieserver_deployment_index }}] call PostgreSQL role"
      include_role:
        name: deploy-postgresql
      vars:
        service_name: '{{ kieserver_db_service }}'
        deployment_name: '{{ kieserver_db_deployment }}'
        postgresql_volume_size: '{{ kieserver_db_size }}'
        postgresql_database: '{{ kieserver_db_name }}'
        postgresql_user: '{{ kieserver_db_user }}'
        postgresql_pwd: '{{ kieserver_db_pwd }}'
      when: kieserver_db_type == "PostgreSQL"

    - name: "[KIE SERVER {{ kieserver_deployment_index }}] call MySQL role"
      include_role:
        name: deploy-mysql
      vars:
        service_name: '{{ kieserver_db_service }}'
        deployment_name: '{{ kieserver_db_deployment }}'
        mysql_volume_size: '{{ kieserver_db_size }}'
        mysql_database: '{{ kieserver_db_name }}'
        mysql_user: '{{ kieserver_db_user }}'
        mysql_pwd: '{{ kieserver_db_pwd }}'
      when: kieserver_db_type == "MySQL"

    - name: "[KIE SERVER {{ kieserver_deployment_index }}] call AMQ role"
      include_role:
        name: deploy-amq
      vars:
        application_name_amq: '{{ kieserver_service_name }}-amq'
        amq_console_service: '{{ kieserver_service_name }}-amq-jolokia'
        amq_service_name: '{{ kieserver_service_name }}-amq'
        amq_broker_name: '{{ kieserver_service_name }}-amq-broker'
        amq_queues: '{{ kieserver_jms_amq_queues }}'
        amq_user: '{{ kieserver_jms_username }}'
        amq_pwd: '{{ kieserver_jms_password }}'
      when: enable_kieserver_jms_integration

    - name: "[KIE SERVER {{ kieserver_deployment_index }}] configure S2I"
      include_tasks: s2i.yml
      when: kieserver_s2i

    - name: "[KIE SERVER {{ kieserver_deployment_index }}] set kieserver state to {{ state }}"
      k8s:
        state: '{{ state }}'
        definition: "{{ lookup('template', 'kieserver-dc.yml.j2') | from_yaml }}"

  when: not provision_failed
