---
- name: "[KIE SERVER {{ kieserver_deployment_index }}] set service state to {{ state }}"
  k8s:
    state: '{{ state }}'
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ kieserver_deployment_name }}'
        namespace: '{{ namespace }}'
        labels:
          app: '{{ kieserver_deployment_name }}'
          application: '{{ application_name }}'
          service: '{{ kieserver_service_name }}'
        annotations:
          description: All the KIE server web server's ports.
      spec:
        selector:
          deploymentConfig: '{{ kieserver_deployment_name }}'
        ports:
          - name: http
            port: 8080
            target_port: 8080
          - name: https
            port: 8443
            target_port: 8443

- name: "[KIE SERVER {{ kieserver_deployment_index }}] set PING service state to {{ state }}"
  when: _apb_plan_id != 'trial'
  k8s:
    state: '{{ state }}'
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ kieserver_deployment_name }}-ping'
        namespace: '{{ namespace }}'
        labels:
          app: '{{ kieserver_deployment_name }}'
          application: '{{ application_name }}'
          service: '{{ kieserver_service_name }}'
        annotations:
          service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
          description: "The JGroups ping port for clustering."
      spec:
        selector:
          deploymentConfig: '{{ kieserver_deployment_name }}'
        ports:
          - name: ping
            port: 8888
            targetPort: 8888
