---
- name: "[SMART ROUTER] check requirements"
  include_role:
    name: check-image-requirements
  vars:
    image_namespace: "{{ smartrouter_image_namespace }}"
    image_name: "{{ smartrouter_image_name }}"
    image_tag: "{{ smartrouter_image_tag }}"
  when: state == "present"

- name: "[SMART ROUTER] configure application"
  block:
    - name: "[SMART ROUTER] configure services"
      include_tasks: services.yml

    - name: "[SMART ROUTER] configure routes"
      include_tasks: routes.yml

    - name: "[SMART ROUTER] configure persistence"
      include_tasks: persistence.yml
      when: smartrouter_volume_size != ""

    - name: "[SMART ROUTER] deploy smart router"
      openshift_raw:
        state: '{{ state }}'
        definition: "{{ lookup('template', 'smartrouter-dc.yml.j2') | from_yaml }}"
  when: not provision_failed
